import {
  NEO_B$_CONTRACT_ADDRESS,
  NEO_BNEO_CONTRACT_ADDRESS,
  NEO_FRANK_CONTRACT_ADDRESS,
  NEO_FWBTC_CONTRACT_ADDRESS,
  NEO_FWETH_CONTRACT_ADDRESS,
  NEO_GAS_CONTRACT_ADDRESS,
  NEO_GLC_CONTRACT_ADDRESS,
  NEO_HIST_CONTRACT_ADDRESS,
  NEO_HOOD_CONTRACT_ADDRESS,
  NEO_LITH_CONTRACT_ADDRESS,
  NEO_MAG_CONTRACT_ADDRESS,
  NEO_MAXI_CONTRACT_ADDRESS,
  NEO_N3F_CONTRACT_ADDRESS,
  NEO_NEP_CONTRACT_ADDRESS,
  NEO_NUDES_CONTRACT_ADDRESS,
  NEO_PEPE_CONTRACT_ADDRESSH,
  NEO_SCHRUTE_CONTRACT_ADDRESSH,
  NEO_TED_CONTRACT_ADDRESS,
  NEO_TGAS_CONTRACT_ADDRESS,
  NEO_TTM_CONTRACT_ADDRESS,
  NEO_USDT_CONTRACT_ADDRESS,
  NEO_WATT_CONTRACT_ADDRESS,
  NEO__7F_CONTRACT_ADDRESS,
} from "./neo-contracts";

import { MAINNET } from "../../../consts/global";

export const NEO_MAINNET_NEP_TOKEN_METADATA = {
  hash: NEO_NEP_CONTRACT_ADDRESS[MAINNET],
  symbol: "NEP",
  icon: "/symbols/nep.png",
  decimals: 8,
};

export const NEO_MAINNET_BNEO_METADATA = {
  hash: NEO_BNEO_CONTRACT_ADDRESS[MAINNET],
  symbol: "bNEO",
  icon: "/symbols/bneo.jpeg",
  decimals: 8,
};

export const NEO_MAINNET_TOKENS_METADATA_MAP = {
  [NEO_NEP_CONTRACT_ADDRESS[MAINNET]]: {
    ...NEO_MAINNET_NEP_TOKEN_METADATA,
    pairs: [
      NEO_BNEO_CONTRACT_ADDRESS[MAINNET],
      NEO_GAS_CONTRACT_ADDRESS,
      NEO_FWBTC_CONTRACT_ADDRESS,
      NEO_FWETH_CONTRACT_ADDRESS,
      NEO_USDT_CONTRACT_ADDRESS,
      NEO_TTM_CONTRACT_ADDRESS,
    ],
  },
  [NEO_TTM_CONTRACT_ADDRESS]: {
    hash: NEO_TTM_CONTRACT_ADDRESS,
    symbol: "TTM",
    icon: "/symbols/ttm.png",
    decimals: 8,
    pairs: [
      NEO_NEP_CONTRACT_ADDRESS[MAINNET],
      NEO_USDT_CONTRACT_ADDRESS,
      NEO_BNEO_CONTRACT_ADDRESS[MAINNET],
    ],
  },
  [NEO_B$_CONTRACT_ADDRESS]: {
    hash: NEO_B$_CONTRACT_ADDRESS,
    symbol: "B$",
    icon: "/symbols/b$.png",
    decimals: 8,
    pairs: [],
  },
  [NEO_BNEO_CONTRACT_ADDRESS[MAINNET]]: {
    ...NEO_MAINNET_BNEO_METADATA,
    pairs: [
      NEO_GAS_CONTRACT_ADDRESS,
      NEO_USDT_CONTRACT_ADDRESS,
      NEO_NEP_CONTRACT_ADDRESS[MAINNET],
      NEO_TTM_CONTRACT_ADDRESS,
    ],
  },
  [NEO_GAS_CONTRACT_ADDRESS]: {
    hash: NEO_GAS_CONTRACT_ADDRESS,
    symbol: "GAS",
    icon: "/symbols/gas.svg",
    decimals: 8,
    pairs: [
      NEO_BNEO_CONTRACT_ADDRESS[MAINNET],
      NEO_NEP_CONTRACT_ADDRESS[MAINNET],
      NEO_USDT_CONTRACT_ADDRESS,
    ],
  },
  [NEO_FWBTC_CONTRACT_ADDRESS]: {
    hash: NEO_FWBTC_CONTRACT_ADDRESS,
    symbol: "fWBTC",
    icon: "/symbols/btc.png",
    decimals: 8,
    pairs: [NEO_NEP_CONTRACT_ADDRESS[MAINNET]],
  },
  [NEO_FWETH_CONTRACT_ADDRESS]: {
    hash: NEO_FWETH_CONTRACT_ADDRESS,
    symbol: "fWETH",
    icon: "/symbols/eth.png",
    decimals: 18,
    pairs: [NEO_NEP_CONTRACT_ADDRESS[MAINNET]],
  },
  [NEO_USDT_CONTRACT_ADDRESS]: {
    hash: NEO_USDT_CONTRACT_ADDRESS,
    symbol: "fUSDT",
    icon: "/symbols/usdt.png",
    decimals: 6,
    pairs: [
      NEO_NEP_CONTRACT_ADDRESS[MAINNET],
      NEO_TTM_CONTRACT_ADDRESS,
      NEO_BNEO_CONTRACT_ADDRESS[MAINNET],
    ],
  },
  [NEO_TGAS_CONTRACT_ADDRESS]: {
    hash: NEO_TGAS_CONTRACT_ADDRESS,
    symbol: "TGAS",
    icon: "/symbols/TGAS.svg",
    decimals: 8,
    pairs: [],
  },
  [NEO_WATT_CONTRACT_ADDRESS]: {
    hash: NEO_WATT_CONTRACT_ADDRESS,
    symbol: "WATT",
    icon: "/symbols/WATT.svg",
    decimals: 8,
    pairs: [],
  },
  [NEO_LITH_CONTRACT_ADDRESS]: {
    hash: NEO_LITH_CONTRACT_ADDRESS,
    symbol: "LITH",
    icon: "/symbols/LITH.svg",
    decimals: 8,
    pairs: [],
  },
  [NEO_HIST_CONTRACT_ADDRESS]: {
    hash: NEO_HIST_CONTRACT_ADDRESS,
    symbol: "HIST",
    icon: "/symbols/HIST.svg",
    decimals: 8,
    pairs: [],
  },
  [NEO_MAG_CONTRACT_ADDRESS]: {
    hash: NEO_MAG_CONTRACT_ADDRESS,
    symbol: "MAG",
    icon: "/symbols/MAG.svg",
    decimals: 8,
    pairs: [],
  },
  [NEO_HOOD_CONTRACT_ADDRESS]: {
    hash: NEO_HOOD_CONTRACT_ADDRESS,
    symbol: "HOOD",
    icon: "/symbols/hood.png",
    decimals: 8,
    pairs: [],
  },
  [NEO_FRANK_CONTRACT_ADDRESS]: {
    hash: NEO_FRANK_CONTRACT_ADDRESS,
    symbol: "frank",
    icon: "/symbols/frank.png",
    decimals: 8,
    pairs: [],
  },
  [NEO_SCHRUTE_CONTRACT_ADDRESSH]: {
    hash: NEO_SCHRUTE_CONTRACT_ADDRESSH,
    symbol: "SCHRUTE",
    icon: "/symbols/SCHRUTE.png",
    decimals: 2,
    pairs: [],
  },
  // [NEO_NUDES_CONTRACT_ADDRESS]: {
  //   hash: NEO_NUDES_CONTRACT_ADDRESS,
  //   symbol: "TIPS",
  //   icon: "/symbols/tips.svg",
  //   decimals: 8,
  //   pairs: [],
  // },
  // [NEO_TED_CONTRACT_ADDRESS]: {
  //   hash: NEO_TED_CONTRACT_ADDRESS,
  //   symbol: "TEDS",
  //   icon: "/symbols/ted.png",
  //   decimals: 8,
  //   pairs: [],
  // },
  // [NEO_MAXI_CONTRACT_ADDRESS]: {
  //   hash: NEO_MAXI_CONTRACT_ADDRESS,
  //   symbol: "MAXI",
  //   icon: "/symbols/maxi.png",
  //   decimals: 8,
  //   pairs: [],
  // },

  // [NEO_N3F_CONTRACT_ADDRESS]: {
  //   hash: NEO_N3F_CONTRACT_ADDRESS,
  //   symbol: "N3F",
  //   icon: "/symbols/n3f.jpg",
  //   decimals: 8,
  //   pairs: [],
  // },
  // [NEO_GLC_CONTRACT_ADDRESS]: {
  //   hash: NEO_GLC_CONTRACT_ADDRESS,
  //   symbol: "GLC",
  //   icon: "/symbols/glc.png",
  //   decimals: 8,
  //   pairs: [],
  // },
  // [NEO__7F_CONTRACT_ADDRESS]: {
  //   hash: NEO__7F_CONTRACT_ADDRESS,
  //   symbol: "7f",
  //   icon: "/symbols/7f.png",
  //   decimals: 8,
  //   pairs: [],
  // },
  // [NEO_PEPE_CONTRACT_ADDRESSH]: {
  //   hash: NEO_PEPE_CONTRACT_ADDRESSH,
  //   symbol: "pepe",
  //   icon: "/symbols/pepe.png",
  //   decimals: 18,
  //   pairs: [],
  // },
};
