import {
  POLYGON_TESTNET_BRIDGE_CONTRACT_ADDRESS,
  POLYGON_TESTNET_FARM_CONTRACT_ADDRESS,
  POLYGON_TESTNET_FNEO_CONTRACT_ADDRESS,
  POLYGON_TESTNET_NEP_CONTRACT_ADDRESS,
  POLYGON_TESTNET_SMITH_CONTRACT_ADDRESS,
  POLYGON_TESTNET_SWAP_CONTRACT_ADDRESS,
  POLYGON_TESTNET_TOKEN_METADATA_MAP,
} from "./testnet";
import {
  POLYGON_MAINNET_BRIDGE_CONTRACT_ADDRESS,
  POLYGON_MAINNET_FARM_CONTRACT_ADDRESS,
  POLYGON_MAINNET_FNEO_CONTRACT_ADDRESS,
  POLYGON_MAINNET_NEP_CONTRACT_ADDRESS,
  POLYGON_MAINNET_SMITH_CONTRACT_ADDRESS,
  POLYGON_MAINNET_SWAP_CONTRACT_ADDRESS,
  POLYGON_MAINNET_TOKEN_METADATA_MAP,
} from "./mainnet";

import {
  MAINNET,
  TESTNET,
  SWAP,
  FARM,
  BRIDGE,
  SMITH,
} from "../../../consts/global";

export const POLYGON_TOKENS_METADATA_MAP = {
  [MAINNET]: POLYGON_MAINNET_TOKEN_METADATA_MAP,
  [TESTNET]: POLYGON_TESTNET_TOKEN_METADATA_MAP,
};

export const POLYGON_CONTRACT_MAP = {
  [MAINNET]: {
    [SWAP]: POLYGON_MAINNET_SWAP_CONTRACT_ADDRESS,
    [FARM]: POLYGON_MAINNET_FARM_CONTRACT_ADDRESS,
    [BRIDGE]: POLYGON_MAINNET_BRIDGE_CONTRACT_ADDRESS,
    [SMITH]: POLYGON_MAINNET_SMITH_CONTRACT_ADDRESS,
  },
  [TESTNET]: {
    [SWAP]: POLYGON_TESTNET_SWAP_CONTRACT_ADDRESS,
    [FARM]: POLYGON_TESTNET_FARM_CONTRACT_ADDRESS,
    [BRIDGE]: POLYGON_TESTNET_BRIDGE_CONTRACT_ADDRESS,
    [SMITH]: POLYGON_TESTNET_SMITH_CONTRACT_ADDRESS,
  },
};

export const POLYGON_SWAP_TOKENS_MAP = {
  [MAINNET]: Object.keys(POLYGON_TOKENS_METADATA_MAP[MAINNET]).map((key) => {
    return POLYGON_TOKENS_METADATA_MAP[MAINNET][key];
  }),
  [TESTNET]: Object.keys(POLYGON_TOKENS_METADATA_MAP[TESTNET]).map((key) => {
    return POLYGON_TOKENS_METADATA_MAP[TESTNET][key];
  }),
};

export const POLYGON_MAINNET_FNEO_CONTRACT_ADDRESSES = {
  [MAINNET]: POLYGON_MAINNET_FNEO_CONTRACT_ADDRESS,
  [TESTNET]: POLYGON_TESTNET_FNEO_CONTRACT_ADDRESS,
};

export const POLYGON_NEP_CONTRACT_ADDRESSES = {
  [MAINNET]: POLYGON_MAINNET_NEP_CONTRACT_ADDRESS,
  [TESTNET]: POLYGON_TESTNET_NEP_CONTRACT_ADDRESS,
};
