// contracts
export const POLYGON_MAINNET_SWAP_CONTRACT_ADDRESS =
  "0x67dee0d471d516221ef107c0d7ab6ce538cbc4ec";
export const POLYGON_MAINNET_BRIDGE_CONTRACT_ADDRESS =
  "0x89Bf4EB7207167339A5DC4b2dBF8003148380F40";
export const POLYGON_MAINNET_SMITH_CONTRACT_ADDRESS =
  "0x10d597c79A8d5f7c993ef6569cCD1EDf7a1bB1a2";
export const POLYGON_MAINNET_FARM_CONTRACT_ADDRESS = "";

// tokens
export const POLYGON_MAINNET_FNEO_CONTRACT_ADDRESS = "";
export const POLYGON_MAINNET_NEP_CONTRACT_ADDRESS =
  "0x8f6E6B2e36fbCB1e03BBc21009a8c03Dce8cf1B6";
export const POLYGON_MAINNET_USDT_CONTRACT_ADDRESS =
  "0xc2132d05d31c914a87c6611c10748aeb04b58e8f";
export const POLYGON_MAINNET_WMATIC_CONTRACT_ADDRESS =
  "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270";
export const POLYGON_MAINNET_WBTC_CONTRACT_ADDRESS =
  "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6";
export const POLYGON_MAINNET_WETH_CONTRACT_ADDRESS =
  "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619";

export const POLYGON_MAINNET_NEP_TOKEN_METADATA = {
  hash: POLYGON_MAINNET_NEP_CONTRACT_ADDRESS,
  symbol: "NEP",
  icon: "/symbols/nep.png",
  decimals: 8,
};

const POLYGON_MAINNET_USDT_TOKEN_METADATA = {
  hash: POLYGON_MAINNET_USDT_CONTRACT_ADDRESS,
  symbol: "USDT",
  icon: "/symbols/usdt.png",
  decimals: 6,
};
const POLYGON_MAINNET_WMATIC_TOKEN_METADATA = {
  hash: POLYGON_MAINNET_WMATIC_CONTRACT_ADDRESS,
  symbol: "WMATIC",
  icon: "/symbols/wMatic.png",
  decimals: 18,
};
const POLYGON_MAINNET_WETH_TOKEN_METADATA = {
  hash: POLYGON_MAINNET_WETH_CONTRACT_ADDRESS,
  symbol: "WETH",
  icon: "/symbols/eth.png",
  decimals: 18,
};
const POLYGON_MAINNET_WBTC_TOKEN_METADATA = {
  hash: POLYGON_MAINNET_WBTC_CONTRACT_ADDRESS,
  symbol: "WBTC",
  icon: "/symbols/btc.png",
  decimals: 8,
};

export const POLYGON_MAINNET_TOKEN_METADATA_MAP = {
  [POLYGON_MAINNET_WBTC_CONTRACT_ADDRESS]: {
    ...POLYGON_MAINNET_WBTC_TOKEN_METADATA,
  },
  [POLYGON_MAINNET_WETH_CONTRACT_ADDRESS]: {
    ...POLYGON_MAINNET_WETH_TOKEN_METADATA,
  },
  [POLYGON_MAINNET_USDT_CONTRACT_ADDRESS]: {
    ...POLYGON_MAINNET_USDT_TOKEN_METADATA,
  },
  [POLYGON_MAINNET_WMATIC_CONTRACT_ADDRESS]: {
    ...POLYGON_MAINNET_WMATIC_TOKEN_METADATA,
  },
  [POLYGON_MAINNET_NEP_CONTRACT_ADDRESS]: {
    ...POLYGON_MAINNET_NEP_TOKEN_METADATA,
  },
};
