import {
  NEOX_MAINNET_CONTRACTS,
  NEOX_MAINNET_SWAP_TOKEN_MAP,
  NEOX_MAINNET_TOKEN_METADATA_MAP,
} from "./mainnet";

import { MAINNET, TESTNET, SMITH, SWAP, FARM } from "../../../consts/global";

export const NEOX_NEP_CONTRACT_ADDRESSES = {
  [MAINNET]: NEOX_MAINNET_CONTRACTS.NEP,
  [TESTNET]: NEOX_MAINNET_CONTRACTS.NEP,
};

export const NEOX_CONTRACT_MAP = {
  [MAINNET]: {
    [SMITH]: NEOX_MAINNET_CONTRACTS.SMITH,
    [SWAP]: NEOX_MAINNET_CONTRACTS.SWAP,
    [FARM]: NEOX_MAINNET_CONTRACTS.FARM,
  },
  [TESTNET]: {
    [SMITH]: NEOX_MAINNET_CONTRACTS.SMITH,
    [SWAP]: NEOX_MAINNET_CONTRACTS.SWAP,
    [FARM]: NEOX_MAINNET_CONTRACTS.FARM,
  },
};

export const NEOX_TOKENS_MAP = {
  [MAINNET]: NEOX_MAINNET_TOKEN_METADATA_MAP,
  [TESTNET]: NEOX_MAINNET_TOKEN_METADATA_MAP,
};

export const NEOX_SWAP_TOKENS_MAP = {
  [MAINNET]: NEOX_MAINNET_SWAP_TOKEN_MAP,
  [TESTNET]: NEOX_MAINNET_SWAP_TOKEN_MAP,
};
