
export const BOYZ_RARITY = {
	"background": [
		"Sky",
		"Underworld",
		"Neo",
		"White",
		"Purple",
		"Pink",
		"Red",
		"Orange",
		"Yellow",
		"Green",
		"Blue",
		"Grey",
		"Mint",
		"Black",
	],
	"body": [
		"Dark Skin",
		"Light Skin",
		"Tan Skin",
	],
	"clothing": [
		"Hacker Hoodie",
		"Bear Hoodie",
		"Spacesuit",
		"Outlaw Shirt",
		"Scarf",
		"White FTW Sweater",
		"Sailor",
		"White Rune Sweater",
		"Black Rune Sweater",
		"White Rune Hoodie",
		"Black Rune Hoodie",
		"Black Rune Sweater",
		"Colorful Sweater",
		"None",
		"White FTW Hoodie",
		"Pink Shirt",
		"Suit",
		"Gold Chain",
		"Rocket Sweater",
		"Black FTW Hoodie",
		"Striped Shirt",
		"Silver Chain",
		"Orange Shirt",
		"Retro Sweater",
		"Party Shirt",
		"Heart Shirt",
		"Striped Sweater",
		"Candy Shirt",
		"Black Turtleneck",
		"Green Collar",
		"Neo Shirt",
		"White Turtleneck",
		"Pink Hoodie",
		"Tank Top",
		"Grey Shirt",
		"Jersey",
		"BW Hoodie",
		"Tracksuit",
		"Green Hoodie",
	],
	"head": [
		"Black Headphones",
		"Blonde Hair",
		"Pink Headphones",
		"Red Headphones",
		"Green Headphones",
		"Space Helmet",
		"Santa Hat",
		"Space Warrior Hair",
		"Wreathe",
		"Viking Helmet",
		"Little Horns",
		"Halo",
		"Wizard Hat",
		"Crown",
		"Party Hat",
		"Pilot Goggles",
		"Horns",
		"Police Hat",
		"Outlaw Hat",
		"M Hat",
		"BW Afro",
		"Helicopter Hat",
		"Army Helmet",
		"Black Hair",
		"Clown Hair",
		"Afro",
		"Neo Hat",
		"Top Hat",
		"Orange Hat",
		"Red Hat",
		"Beret",
		"Grey Hat",
		"Explorer Hat",
		"Purple Messy Hair",
		"Sunset Hat",
		"Bandana",
		"Durag",
		"Black Mohawk",
		"Headband",
		"Blue Messy Hair",
		"Brown Mohawk",
		"White Hat",
		"Bald",
		"Black Messy Hair",
		"Beanie",
		"Dreads",
		"Red Messy Hair",
		"String Hair",
	],
	"eyes": [
		"Scuba Gear",
		"Scouter",
		"Tears",
		"Ninja",
		"Gold Glasses",
		"VR",
		"Hearts",
		"3D Glasses",
		"Neo Glasses",
		"Laser",
		"Neo's Glasses",
		"White Sunset Glasses",
		"Pixel Glasses",
		"Green",
		"Red",
		"Blue Glasses",
		"Sunset Glasses",
		"Rainbow Glasses",
		"Green Glasses",
		"White Glasses",
		"Normal",
		"Cool",
	],
	"mouth": [
		"Green Smoke",
		"Pipe",
		"Goatee",
		"White Beard",
		"Black Beard",
		"Brown Beard",
		"5 O'clock Shadow",
		"Smoke",
		"Unimpressed",
		"Smirk",
	],
	"accessory": [
		"Clown Nose",
		"Gold Earing",
		"Silver Earing",
		"None",
	],
}
