import {
	BNEO_SCRIPT_HASH,
	FRANK_SCRIPT_HASH,
	FWBTC_SCRIPT_HASH,
	FWETH_SCRIPT_HASH,
	GAS_SCRIPT_HASH,
	GLC_SCRIPT_HASH,
	HIST_SCRIPT_HASH,
	HOOD_SCRIPT_HASH,
	LITH_SCRIPT_HASH,
	MAG_SCRIPT_HASH,
	MAXI_SCRIPT_HASH,
	N3F_SCRIPT_HASH, NEO_SCRIPT_HASH,
	NEP_SCRIPT_HASH,
	NUDES_SCRIPT_HASH,
	TED_SCRIPT_HASH,
	TGAS_SCRIPT_HASH,
	TTM_SCRIPT_HASH,
	USDT_SCRIPT_HASH,
	WATT_SCRIPT_HASH,
} from "../../../consts/nep17-list";
import {
  MAINNET,
  TOKEN_CATEGORY_GENERAL,
  TOKEN_CATEGORY_METAVERSE,
  TOKEN_CATEGORY_STARTUPS,
} from "../../../consts";
export const MAINNET_TOKEN_LIST = {
  [NEP_SCRIPT_HASH[MAINNET]]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: NEP_SCRIPT_HASH[MAINNET],
    symbol: "NEP",
    icon: "/symbols/nep.png",
    decimals: 8,
  },
  [BNEO_SCRIPT_HASH[MAINNET]]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: BNEO_SCRIPT_HASH[MAINNET],
    symbol: "bNEO",
    icon: "/symbols/bneo.jpeg",
    decimals: 8,
  },
	[NEO_SCRIPT_HASH]: {
		category: TOKEN_CATEGORY_GENERAL,
		hash: NEO_SCRIPT_HASH,
		symbol: "NEO",
		icon: "/symbols/neo.svg",
		decimals: 0,
	},
  [GAS_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: GAS_SCRIPT_HASH,
    symbol: "GAS",
    icon: "/symbols/gas.svg",
    decimals: 8,
  },
  [FWBTC_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: FWBTC_SCRIPT_HASH,
    symbol: "fWBTC",
    icon: "/symbols/btc.png",
    decimals: 8,
  },
  [FWETH_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: FWETH_SCRIPT_HASH,
    symbol: "fWETH",
    icon: "/symbols/eth.png",
    decimals: 18,
  },
  [USDT_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_GENERAL,
    hash: USDT_SCRIPT_HASH,
    symbol: "fUSDT",
    icon: "/symbols/usdt.png",
    decimals: 6,
  },
  [TTM_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: TTM_SCRIPT_HASH,
    symbol: "TTM",
    icon: "/symbols/ttm.png",
    decimals: 8,
  },
  [TGAS_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: TGAS_SCRIPT_HASH,
    symbol: "TGAS",
    icon: "/symbols/TGAS.svg",
    decimals: 8,
  },
  [WATT_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: WATT_SCRIPT_HASH,
    symbol: "WATT",
    icon: "/symbols/WATT.svg",
    decimals: 8,
  },
  [LITH_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: LITH_SCRIPT_HASH,
    symbol: "LITH",
    icon: "/symbols/LITH.svg",
    decimals: 8,
  },
  [HIST_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: HIST_SCRIPT_HASH,
    symbol: "HIST",
    icon: "/symbols/HIST.svg",
    decimals: 8,
  },
  [MAG_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_METAVERSE,
    hash: MAG_SCRIPT_HASH,
    symbol: "MAG",
    icon: "/symbols/MAG.svg",
    decimals: 8,
  },
  [HOOD_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: HOOD_SCRIPT_HASH,
    symbol: "HOOD",
    icon: "/symbols/hood.png",
    decimals: 8,
  },
  [NUDES_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: NUDES_SCRIPT_HASH,
    symbol: "NUDES",
    icon: "/symbols/nudes.png",
    decimals: 8,
  },
  [TED_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: TED_SCRIPT_HASH,
    symbol: "TEDS",
    icon: "/symbols/ted.png",
    decimals: 8,
  },
  [MAXI_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: MAXI_SCRIPT_HASH,
    symbol: "MAXI",
    icon: "/symbols/maxi.png",
    decimals: 8,
  },
  [FRANK_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: FRANK_SCRIPT_HASH,
    symbol: "frank",
    icon: "/symbols/frank.png",
    decimals: 8,
  },
  [N3F_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: N3F_SCRIPT_HASH,
    symbol: "N3F",
    icon: "/symbols/n3f.jpg",
    decimals: 8,
  },
  // [B$_SCRIPT_HASH]: {
  // 	category: TOKEN_CATEGORY_STARTUPS,
  // 	hash: B$_SCRIPT_HASH,
  // 	symbol: "B$",
  // 	icon: "/symbols/battle.png",
  // 	decimals: 8,
  // },
  [GLC_SCRIPT_HASH]: {
    category: TOKEN_CATEGORY_STARTUPS,
    hash: GLC_SCRIPT_HASH,
    symbol: "GLC",
    icon: "/symbols/glc.png",
    decimals: 8,
  },
};
